export const SITE_NAME = 'Apple Valley';
export const SITE_TAGLINE = 'Stay Above the Clouds';

export const ROOM_CATEGORIES = [
  {
    id: 'deluxe-kodai-valley',
    name: 'Deluxe Kodai Valley Room',
    description: 'A warm hill-view room facing the misty Kodaikanal valley, ideal for couples and small families.',
    basePrice: 3800,
    maxOccupancy: 2,
    bedType: 'King',
    size: 280,
  },
  {
    id: 'premium-mist-balcony',
    name: 'Premium Mist Balcony Room',
    description: 'Private balcony stay with morning mist, eucalyptus breeze, and views towards the Palani hills.',
    basePrice: 5200,
    maxOccupancy: 2,
    bedType: 'King',
    size: 320,
  },
  {
    id: 'tamil-nadu-family-cottage',
    name: 'Tamil Nadu Family Cottage',
    description: 'Spacious cottage for families visiting Kodai Lake, Bryant Park, Pine Forest, and nearby viewpoints.',
    basePrice: 7200,
    maxOccupancy: 4,
    bedType: '2 Double',
    size: 450,
  },
  {
    id: 'kurinji-honeymoon-suite',
    name: 'Kurinji Honeymoon Suite',
    description: 'Romantic suite inspired by Kurinji blooms, with a cozy sit-out and premium hill-station amenities.',
    basePrice: 8600,
    maxOccupancy: 2,
    bedType: 'King',
    size: 400,
  },
  {
    id: 'standard-kodai-comfort',
    name: 'Standard Kodai Comfort Room',
    description: 'Affordable and comfortable room for quick Kodaikanal trips, trekking groups, and weekend travelers.',
    basePrice: 2400,
    maxOccupancy: 2,
    bedType: 'Queen',
    size: 180,
  },
];

export const DEFAULT_AMENITIES = [
  'Kodai Valley View',
  'Palani Hills View',
  'Room Heater',
  'Hot Water',
  'WiFi',
  'TV with Cable',
  'Tea/Coffee Maker',
  'Filter Coffee Sachets',
  'Balcony',
  'Campfire Access',
  'Seating Area',
  'Work Desk',
  'Private Bathroom',
  'Toiletries',
  'Hair Dryer',
  '24/7 Room Service',
  'Sofa Bed',
];

export const ATTRACTIONS_DATA = [
  {
    name: 'Kodai Lake',
    slug: 'kodai-lake',
    description: 'A star-shaped man-made lake in the heart of Kodaikanal. Perfect for boating, cycling along the promenade, and enjoying sunset views. The lake is the center of all activities in the town.',
    shortDescription: 'Star-shaped lake, boating, cycling promenade',
    image: 'https://drive.google.com/file/d/1RhVdjbupf5krWBAcOWVnTCrfAvSXLU-p/view?usp=sharing',
    category: 'nature',
    distance: 0.5,
    visitDuration: '1-2 hours',
    timings: '8:00 AM - 6:00 PM',
    entryFee: 'Boating charges apply',
    bestTimeToVisit: 'Morning and Evening',
    featured: true,
  },
  {
    name: "Coaker's Walk",
    slug: 'coakers-walk',
    description: "A 1 km long paved pedestrian path on the edge of a cliff. On clear days, you can see views of the Virupaksha Peak and the valley below. Walk during early morning for misty views.",
    shortDescription: 'Scenic cliff walk, panoramic valley views',
    image: 'https://images.pexels.com/photos\/2387873/pexels-photo-2387873.jpeg',
    category: 'viewpoint',
    distance: 1.2,
    visitDuration: '30 mins - 1 hour',
    timings: '7:00 AM - 7:00 PM',
    bestTimeToVisit: 'Early Morning',
    featured: true,
  },
  {
    name: 'Bryant Park',
    slug: 'bryant-park',
    description: 'A beautiful botanical garden spread across 20 acres with over 740 species of plants. Famous for its rose garden, annual horticultural shows, and the 300-year-old eucalyptus tree.',
    shortDescription: 'Botanical garden, rose collection, boating lake',
    image: 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg',
    category: 'park',
    distance: 2.0,
    visitDuration: '1-2 hours',
    timings: '9:00 AM - 6:00 PM',
    entryFee: 'Minimal entry fee',
    featured: true,
  },
  {
    name: 'Pillar Rocks',
    slug: 'pillar-rocks',
    description: 'Three giant rock pillars standing 400 feet tall offering breathtaking views of the valley below. The viewpoint provides spectacular vistas especially during sunset.',
    shortDescription: 'Giant rock pillars, valley viewpoint',
    image: 'https://images.pexels.com/photos/2583854/pexels-photo-2583854.jpeg',
    category: 'viewpoint',
    distance: 8.0,
    visitDuration: '30-45 mins',
    timings: '9:00 AM - 5:30 PM',
    bestTimeToVisit: 'Afternoon for best visibility',
    featured: true,
  },
  {
    name: 'Pine Forest',
    slug: 'pine-forest',
    description: 'A serene forest of tall pine trees perfect for nature walks and photography. The misty atmosphere creates magical photo opportunities throughout the year.',
    shortDescription: 'Tall pine trees, misty walks, photography',
    image: 'https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg',
    category: 'nature',
    distance: 5.5,
    visitDuration: '30 mins - 1 hour',
    bestTimeToVisit: 'Morning, especially during monsoon',
    featured: false,
  },
  {
    name: 'Guna Caves',
    slug: 'guna-caves',
    description: 'Famous cave formations surrounded by dense forest. Known for their natural rock formations and the movie "Manjummel Boys". Accessible with guided tours.',
    shortDescription: 'Natural caves, forest trails, adventure',
    image: 'https://images.pexels.com/photos/2017802/pexels-photo-2017802.jpeg',
    category: 'cave',
    distance: 10.0,
    visitDuration: '1-2 hours',
    timings: '8:00 AM - 5:00 PM',
    tips: 'Wear comfortable shoes for the trek',
    featured: true,
  },
  {
    name: 'Kurinji Andavar Temple',
    slug: 'kurinji-andavar-temple',
    description: 'A famous temple dedicated to Lord Murugan, known for the rare Kurinji flowers that bloom once every 12 years. Beautiful views of the surrounding hills.',
    shortDescription: 'Lord Murugan temple, Kurinji flowers, hill views',
    image: 'https://images.pexels.com/photos/2159569/pexels-photo-2159569.jpeg',
    category: 'religious',
    distance: 6.0,
    visitDuration: '30-45 mins',
    timings: '7:00 AM - 1:00 PM, 3:00 PM - 8:00 PM',
    featured: false,
  },
];

export const ADDONS_DATA = [
  { name: 'South Indian Breakfast Platter', category: 'dining', price: 350 },
  { name: 'Tamil Nadu Meals Lunch', category: 'dining', price: 450 },
  { name: 'Homestyle Idli Dosa Dinner', category: 'dining', price: 400 },
  { name: 'Kodaikanal Filter Coffee Tray', category: 'dining', price: 220 },
  { name: 'Hill View Candle Light Dinner', category: 'dining', price: 1800 },
  { name: 'Private Campfire with Tea Snacks', category: 'celebration', price: 900 },
  { name: 'Birthday Cake from Kodai Bakery', category: 'celebration', price: 950 },
  { name: 'Jasmine and Rose Room Decoration', category: 'celebration', price: 1300 },
  { name: 'Extra Room Heater', category: 'comfort', price: 350, unit: 'per_night' },
  { name: 'Woollen Blanket Set', category: 'comfort', price: 180, unit: 'per_night' },
  { name: 'Extra Bed with Breakfast', category: 'comfort', price: 750 },
  { name: 'Kodai Lake Pickup and Drop', category: 'transport', price: 700 },
  { name: 'Kodaikanal Local Cab - Half Day', category: 'transport', price: 1800 },
  { name: 'Kodaikanal Local Cab - Full Day', category: 'transport', price: 3200 },
  { name: 'Madurai Railway/Airport Pickup', category: 'transport', price: 5200 },
];

export const PACKAGES_DATA = [
  {
    name: 'Kodai Couple Mist Stay',
    slug: 'kodai-couple-mist-stay',
    description: 'A romantic 2-night Kodaikanal escape with misty balcony views, filter coffee mornings, and a private hill-view dinner.',
    shortDescription: 'Romantic Kodai stay with dinner, coffee, and room decor',
    nights: 2,
    price: 10999,
    originalPrice: 13999,
    inclusions: [
      'Premium Mist Balcony Room',
      'Daily Breakfast',
      'Hill View Candle Light Dinner once',
      'Jasmine and Rose Room Decoration',
      'Kodaikanal Filter Coffee Tray',
      'Kodai Lake evening drop',
    ],
    maxOccupancy: 2,
    featured: true,
  },
  {
    name: 'Kodaikanal Family Holiday',
    slug: 'kodaikanal-family-holiday',
    description: 'A relaxed family holiday with cottage stay, South Indian meals, and sightseeing around Kodai Lake, Bryant Park, Pine Forest, and Pillar Rocks.',
    shortDescription: '3-night family cottage with meals and sightseeing',
    nights: 3,
    price: 22999,
    originalPrice: 28999,
    inclusions: [
      'Tamil Nadu Family Cottage',
      'Daily South Indian Breakfast',
      'One Tamil Nadu Meals Lunch',
      'Kodaikanal Local Cab - Full Day',
      'Private Campfire with Tea Snacks',
      'Kids snacks hamper',
    ],
    maxOccupancy: 4,
    featured: true,
  },
  {
    name: 'Chennai to Kodai Weekend Escape',
    slug: 'chennai-kodai-weekend',
    description: 'A quick hill-station reset for guests coming from Chennai, Madurai, Coimbatore, or Trichy. Simple, quiet, and close to key Kodai sights.',
    shortDescription: '2-night South Indian hill-station weekend',
    nights: 2,
    price: 8499,
    originalPrice: 10499,
    inclusions: [
      'Deluxe Kodai Valley Room',
      'Daily Breakfast',
      'Evening Filter Coffee',
      'Coaker\'s Walk and Bryant Park drop',
      '10% Discount on Add-ons',
    ],
    maxOccupancy: 2,
    featured: false,
  },
  {
    name: 'Kurinji Honeymoon Retreat',
    slug: 'kurinji-honeymoon-retreat',
    description: 'A premium honeymoon retreat inspired by Kodaikanal\'s Kurinji flowers, with suite stay, romantic decor, private dinners, and quiet viewpoints.',
    shortDescription: 'Luxury Kodai honeymoon with suite and romantic setups',
    nights: 3,
    price: 27999,
    originalPrice: 34999,
    inclusions: [
      'Kurinji Honeymoon Suite',
      'Daily Breakfast in Bed',
      '2 Hill View Candle Light Dinners',
      'Jasmine and Rose Room Decoration',
      'Kodaikanal Filter Coffee Tray',
      'Private Campfire',
      'Pillar Rocks and Pine Forest cab',
    ],
    maxOccupancy: 2,
    featured: true,
  },
  {
    name: 'Madurai Team Retreat',
    slug: 'madurai-team-retreat',
    description: 'A practical team retreat for South Tamil Nadu groups with meeting support, hill-view rooms, tea breaks, and local sightseeing options.',
    shortDescription: 'Corporate/team retreat with meals and meeting support',
    nights: 2,
    price: 5200,
    originalPrice: 6500,
    inclusions: [
      'Deluxe Kodai Valley Room - Group Rate',
      'Daily Breakfast and Tamil Nadu Meals Lunch',
      'Conference Room (4 hrs/day)',
      'AV Equipment',
      'Evening Filter Coffee and Snacks',
      'Wi-Fi',
    ],
    maxOccupancy: 2,
    featured: false,
  },
];

export const SEASONS_DATA = [
  { name: 'Summer Vacation', type: 'summer', startDate: '2024-04-01', endDate: '2024-06-15', multiplier: 1.25 },
  { name: 'Weekend Pricing', type: 'weekend', startDate: '2024-01-01', endDate: '2024-12-31', multiplier: 1.15 },
  { name: 'Diwali Week', type: 'festival', startDate: '2024-10-25', endDate: '2024-11-05', multiplier: 1.3 },
  { name: 'Christmas Week', type: 'festival', startDate: '2024-12-20', endDate: '2025-01-05', multiplier: 1.35 },
  { name: 'Pongal Week', type: 'festival', startDate: '2024-01-10', endDate: '2024-01-17', multiplier: 1.25 },
];

export const TAX_RATE = 0.12; // 12% GST

export const CHECK_IN_TIME = '14:00';
export const CHECK_OUT_TIME = '11:00';

export const CANCELLATION_POLICY = {
  freeCancellationDays: 3,
  cancellationChargePercent: 20,
  noRefundDays: 1,
};

export const WHATSAPP_MESSAGE_TEMPLATES = {
  bookingConfirmation: (bookingId: string, guestName: string) =>
    `Dear ${guestName}, your booking at Apple Valley is confirmed!\n\nBooking ID: ${bookingId}\n\nWe look forward to hosting you. For any queries, reply to this message.`,
  checkInReminder: (guestName: string, date: string) =>
    `Dear ${guestName}, this is a reminder about your check-in at Apple Valley tomorrow (${date}). Check-in time is 2 PM. See you soon!`,
  reviewRequest: (guestName: string) =>
    `Dear ${guestName}, thank you for staying with us at Apple Valley! We hope you had a wonderful time. Would you like to share your experience?`,
};
