import { RoomType } from '@/types';

export const SITE_NAME = 'Apple Valley';
export const SITE_TAGLINE = 'Stay Above the Clouds';

export const ROOM_CATEGORIES = [
  {
    id: 'deluxe-hill-view',
    name: 'Deluxe Hill View Room',
    description: 'Wake up to panoramic views of the misty hills',
    basePrice: 3500,
    maxOccupancy: 2,
    bedType: 'King',
    size: 280,
  },
  {
    id: 'premium-balcony',
    name: 'Premium Balcony Room',
    description: 'Step out to your private balcony facing the valley',
    basePrice: 4500,
    maxOccupancy: 2,
    bedType: 'King',
    size: 320,
  },
  {
    id: 'family-cottage',
    name: 'Family Cottage',
    description: 'Spacious wooden cottage perfect for families',
    basePrice: 6000,
    maxOccupancy: 4,
    bedType: '2 Double',
    size: 450,
  },
  {
    id: 'honeymoon-suite',
    name: 'Honeymoon Suite',
    description: 'Romantic retreat with lake views and premium amenities',
    basePrice: 7500,
    maxOccupancy: 2,
    bedType: 'King',
    size: 400,
  },
  {
    id: 'budget-standard',
    name: 'Budget Standard Room',
    description: 'Comfortable and affordable hill-station stay',
    basePrice: 2000,
    maxOccupancy: 2,
    bedType: 'Queen',
    size: 180,
  },
];

export const DEFAULT_AMENITIES = [
  'Lake View',
  'Mountain View',
  'Room Heater',
  'Hot Water',
  'WiFi',
  'TV with Cable',
  'Tea/Coffee Maker',
  'Mini Bar',
  'Balcony',
  ' fireplace',
  'Seating Area',
  'Work Desk',
  'Private Bathroom',
  'Toiletries',
  'Hair Dryer',
  '24/7 Room Service',
  'Sofa Bed',
];

export const ATTRACTIONS_DATA = [
  {
    name: 'Kodai Lake',
    slug: 'kodai-lake',
    description: 'A star-shaped man-made lake in the heart of Kodaikanal. Perfect for boating, cycling along the promenade, and enjoying sunset views. The lake is the center of all activities in the town.',
    shortDescription: 'Star-shaped lake, boating, cycling promenade',
    image: 'https://drive.google.com/file/d/1RhVdjbupf5krWBAcOWVnTCrfAvSXLU-p/view?usp=sharing',
    category: 'nature',
    distance: 0.5,
    visitDuration: '1-2 hours',
    timings: '8:00 AM - 6:00 PM',
    entryFee: 'Boating charges apply',
    bestTimeToVisit: 'Morning and Evening',
    featured: true,
  },
  {
    name: "Coaker's Walk",
    slug: 'coakers-walk',
    description: "A 1 km long paved pedestrian path on the edge of a cliff. On clear days, you can see views of the Virupaksha Peak and the valley below. Walk during early morning for misty views.",
    shortDescription: 'Scenic cliff walk, panoramic valley views',
    image: 'https://images.pexels.com/photos\/2387873/pexels-photo-2387873.jpeg',
    category: 'viewpoint',
    distance: 1.2,
    visitDuration: '30 mins - 1 hour',
    timings: '7:00 AM - 7:00 PM',
    bestTimeToVisit: 'Early Morning',
    featured: true,
  },
  {
    name: 'Bryant Park',
    slug: 'bryant-park',
    description: 'A beautiful botanical garden spread across 20 acres with over 740 species of plants. Famous for its rose garden, annual horticultural shows, and the 300-year-old eucalyptus tree.',
    shortDescription: 'Botanical garden, rose collection, boating lake',
    image: 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg',
    category: 'park',
    distance: 2.0,
    visitDuration: '1-2 hours',
    timings: '9:00 AM - 6:00 PM',
    entryFee: 'Minimal entry fee',
    featured: true,
  },
  {
    name: 'Pillar Rocks',
    slug: 'pillar-rocks',
    description: 'Three giant rock pillars standing 400 feet tall offering breathtaking views of the valley below. The viewpoint provides spectacular vistas especially during sunset.',
    shortDescription: 'Giant rock pillars, valley viewpoint',
    image: 'https://images.pexels.com/photos/2583854/pexels-photo-2583854.jpeg',
    category: 'viewpoint',
    distance: 8.0,
    visitDuration: '30-45 mins',
    timings: '9:00 AM - 5:30 PM',
    bestTimeToVisit: 'Afternoon for best visibility',
    featured: true,
  },
  {
    name: 'Pine Forest',
    slug: 'pine-forest',
    description: 'A serene forest of tall pine trees perfect for nature walks and photography. The misty atmosphere creates magical photo opportunities throughout the year.',
    shortDescription: 'Tall pine trees, misty walks, photography',
    image: 'https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg',
    category: 'nature',
    distance: 5.5,
    visitDuration: '30 mins - 1 hour',
    bestTimeToVisit: 'Morning, especially during monsoon',
    featured: false,
  },
  {
    name: 'Guna Caves',
    slug: 'guna-caves',
    description: 'Famous cave formations surrounded by dense forest. Known for their natural rock formations and the movie "Manjummel Boys". Accessible with guided tours.',
    shortDescription: 'Natural caves, forest trails, adventure',
    image: 'https://images.pexels.com/photos/2017802/pexels-photo-2017802.jpeg',
    category: 'cave',
    distance: 10.0,
    visitDuration: '1-2 hours',
    timings: '8:00 AM - 5:00 PM',
    tips: 'Wear comfortable shoes for the trek',
    featured: true,
  },
  {
    name: 'Kurinji Andavar Temple',
    slug: 'kurinji-andavar-temple',
    description: 'A famous temple dedicated to Lord Murugan, known for the rare Kurinji flowers that bloom once every 12 years. Beautiful views of the surrounding hills.',
    shortDescription: 'Lord Murugan temple, Kurinji flowers, hill views',
    image: 'https://images.pexels.com/photos/2159569/pexels-photo-2159569.jpeg',
    category: 'religious',
    distance: 6.0,
    visitDuration: '30-45 mins',
    timings: '7:00 AM - 1:00 PM, 3:00 PM - 8:00 PM',
    featured: false,
  },
];

export const ADDONS_DATA = [
  { name: 'Candle Light Dinner', category: 'dining', price: 1500 },
  { name: 'BBQ Dinner', category: 'dining', price: 1200 },
  { name: 'Campfire', category: 'celebration', price: 500 },
  { name: 'Birthday Cake', category: 'celebration', price: 800 },
  { name: 'Flower Decoration', category: 'celebration', price: 1000 },
  { name: 'Room Heater', category: 'comfort', price: 300, unit: 'per_night' },
  { name: 'Extra Blanket', category: 'comfort', price: 150, unit: 'per_night' },
  { name: 'Extra Bed', category: 'comfort', price: 500 },
  { name: 'Sightseeing Cab - Half Day', category: 'transport', price: 1500 },
  { name: 'Sightseeing Cab - Full Day', category: 'transport', price: 2500 },
  { name: 'Airport/Railway Pickup', category: 'transport', price: 3000 },
];

export const PACKAGES_DATA = [
  {
    name: 'Couple Misty Stay Package',
    slug: 'couple-misty-stay',
    description: 'A romantic 2-night escape designed for couples. Wake up to misty hill views, enjoy a candle-lit dinner, and create memories that last forever.',
    shortDescription: 'Romantic 2-night stay with dinner and decorations',
    nights: 2,
    price: 8999,
    originalPrice: 12000,
    inclusions: [
      'Premium Balcony Room',
      'Daily Breakfast',
      'Candle Light Dinner once',
      'Flower Decoration',
      'Campfire Evening',
      'Welcome Drink on Arrival',
    ],
    maxOccupancy: 2,
    featured: true,
  },
  {
    name: 'Family Vacation Package',
    slug: 'family-vacation',
    description: 'Perfect family getaway with spacious cottage accommodation, fun activities for kids, and sightseeing tour of Kodaikanal\'s best attractions.',
    shortDescription: '3-night family stay with cottage and sightseeing',
    nights: 3,
    price: 19999,
    originalPrice: 25000,
    inclusions: [
      'Family Cottage',
      'Daily Breakfast and Dinner',
      'Full Day Sightseeing Cab',
      'BBQ Evening',
      'Campfire Session',
      'Kids Activity Kit',
    ],
    maxOccupancy: 4,
    featured: true,
  },
  {
    name: 'Weekend Escape Package',
    slug: 'weekend-escape',
    description: 'Quick 2-night refresh from city life. Perfect for professionals seeking a peaceful weekend retreat in the hills.',
    shortDescription: '2-night hill station retreat',
    nights: 2,
    price: 7499,
    originalPrice: 9000,
    inclusions: [
      'Deluxe Hill View Room',
      'Daily Breakfast',
      'Evening Tea/Coffee',
      'Nature Walk Guide',
      '15% Discount on Add-ons',
    ],
    maxOccupancy: 2,
    featured: false,
  },
  {
    name: 'Honeymoon Hill View Package',
    slug: 'honeymoon-hill-view',
    description: 'Begin your forever in the lap of misty hills. Premium suite with rose decorations, private dinners, romantic setups, and magical lake views.',
    shortDescription: 'Luxury honeymoon with premium suite and romantic setups',
    nights: 3,
    price: 24999,
    originalPrice: 32000,
    inclusions: [
      'Honeymoon Suite',
      'Daily Breakfast in Bed',
      '2 Candle Light Dinners',
      'Rose Bed Decoration',
      'Room Fresh Flowers Daily',
      'Chocolate Hamper',
      'Private Campfire',
    ],
    maxOccupancy: 2,
    featured: true,
  },
  {
    name: 'Corporate Refresh Package',
    slug: 'corporate-refresh',
    description: 'Bring your team for a refreshing retreat. Conference facilities, team activities, and comfortable group accommodation.',
    shortDescription: 'Corporate retreat with conference facilities',
    nights: 2,
    price: 4500,
    originalPrice: 5500,
    inclusions: [
      'Deluxe Room (Group Rate)',
      'Daily Breakfast and Lunch',
      'Conference Room (4 hrs/day)',
      'AV Equipment',
      'Evening Team Snacks',
      'Wi-Fi',
    ],
    maxOccupancy: 2,
    featured: false,
  },
];

export const SEASONS_DATA = [
  { name: 'Summer Vacation', type: 'summer', startDate: '2024-04-01', endDate: '2024-06-15', multiplier: 1.25 },
  { name: 'Weekend Pricing', type: 'weekend', startDate: '2024-01-01', endDate: '2024-12-31', multiplier: 1.15 },
  { name: 'Diwali Week', type: 'festival', startDate: '2024-10-25', endDate: '2024-11-05', multiplier: 1.3 },
  { name: 'Christmas Week', type: 'festival', startDate: '2024-12-20', endDate: '2025-01-05', multiplier: 1.35 },
  { name: 'Pongal Week', type: 'festival', startDate: '2024-01-10', endDate: '2024-01-17', multiplier: 1.25 },
];

export const TAX_RATE = 0.12; // 12% GST

export const CHECK_IN_TIME = '14:00';
export const CHECK_OUT_TIME = '11:00';

export const CANCELLATION_POLICY = {
  freeCancellationDays: 3,
  cancellationChargePercent: 20,
  noRefundDays: 1,
};

export const WHATSAPP_MESSAGE_TEMPLATES = {
  bookingConfirmation: (bookingId: string, guestName: string) =>
    `Dear ${guestName}, your booking at Apple Valley is confirmed!\n\nBooking ID: ${bookingId}\n\nWe look forward to hosting you. For any queries, reply to this message.`,
  checkInReminder: (guestName: string, date: string) =>
    `Dear ${guestName}, this is a reminder about your check-in at Apple Valley tomorrow (${date}). Check-in time is 2 PM. See you soon!`,
  reviewRequest: (guestName: string) =>
    `Dear ${guestName}, thank you for staying with us at Apple Valley! We hope you had a wonderful time. Would you like to share your experience?`,
};
